### ISSUE TITLE
Roadmap for initial release

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-domain-language#1]
Below is the skeleton that should be supported at the minimum IMO for this to be reusable in all places

```
var self = {
  parse: parse, // this should accept a JDL string data and output a parsed object same as today required for JHUML
  parseIntermediate: parseIntermediate, // this should be called inside the above method but needs to be exposed as well, this accepts a JDL string and outputs the current pegjs parsed json, this could be used by JDL studio etc
  parseToJson: parseToJson // this could parse the JDL and output an array of Jhipster compatible json entities 
};

```

@MathieuAA what is your idea?

**Comment by deepu105** [comment]
If JHUML can work with `parseJson` then the parse method could be removed and we can rename `parseIntermediate` to `parse`

**Comment by MathieuAA** [comment]
We don't need the #parse method (we already convert what we need from PegJS).
#parseIntermediate should indeed be renamed to #parse.
I don't understand what the role of #parseToJson would be. Would that "automatically" convert JDL data to JSON-for-JHipster JSON?

**Comment by deepu105** [comment]
im thinking from a reusable perspective

1. `parseToJson ` : If this lib can convert JDL to Jhipster entity json it could be used within JHUML and in the new sub generator Im writing in Jhipster (this means all JDL related logic stays in this lib) and you can just concentrate on UML in JHUML
2. There should be a method exposing the direct output from peg parser as well so that we can reuse that in the future, I can try to use in JDL studio as well

**Comment by deepu105** [comment]
This is my current sub generator https://github.com/deepu105/generator-jhipster/blob/jdl/generators/import-jdl/index.js

but I dont like to do the JDL logic here again as its kind of reduntant

**Comment by deepu105** [comment]
If this lib has a `parseToJson` method then in the sub gen I can pass a JDL text to it and get an array of Jhipster entity jsosn which I can pass to the entitry sub generator to scaffold the entities

so this simplifies the sub gen to
```
      parseJDL: function () {
                this.entities = jdl.parseToJson(this.jdlFile, this.databaseType);
                writeJSON(this.entities); // an util method to iterate and write to `.jhipster` folder
            }
        },

        generateEntities: function () {
               // compose entity sub gen here
        }
```

**Comment by MathieuAA** [comment]
In JHipster UML, we only use what's directly returned from PegParser (we know how to read everything, and just convert everything to a more readable data system).
We wouldn't use such a method.
Yes, such a method (what's directly returned by PegJS) should be available (or at least for now).

We could code in client projects instead of here... But like you said, it would be much easier not to do that and just be clients (and be completely JDL-independent).

For JHipster UML, however, it's not that easy. We have an intermediary data system, and we can't put that in this project as it is used for the other parsers. So for me, the services should simply be, for now at least:

```
#parse -> returns what's returned by PegJS (JHipster UML is a consumer)
#parseToJHipsterJSON -> returns what JHipster needs.
```

I'm still unsure about the second one. Should JHipster work a bit? Because if the JSON changes, this project would change too much, and it's not good at all as the consumer projects don't provide interfaces (JHipster UML actually does, but not JHipster). We should decrease the work load as much as possible.
JHipster could have a way of creating the JSON from the missing link like this:

JDL project -> #parse -> ??? -> JHIpster -> JSON

**Comment by deepu105** [comment]
If this project only does a peg parser then there no much value in having
this as a separate project, the peg parser is anyway generated and can be
directly used anywhere as needed.

This is suppose to be a companion utility and as I said earlier I wouldn't
like doing the JDL intermediate parsing in multiple places especially not
in JHipster as its already too heavy to maintain.

i saw your JHUML code and I dont see why it wouldn't work if we do it here.
You have a DSL parser which does intermediate parsing you just need to move
that here with some simplification and then you can directly do a one step
conversion and get the jhipster json using this lib and the same can be
done in a sub generator as well.

Another option is to remove the jdl option completely from Jhuml and use it
purely from the sub generator that way you can remove all jdl related code
from Jhuml and move ot here.

In either case there is no point in having this repo if it doesn't convert
JDL to an usable form, and currently the jhipster entity json is the usable
form.

I still dont see why you are hesitant!

**Comment by MathieuAA** [comment]
I'm not. Just wondering how to reduce the coupling between producer and consumers.

**Comment by MathieuAA** [comment]
Update, when you said "usable form", did you have something in mind? Because I do, but I don't know how to make something useful for JHipster. For us, a usable form is the intermediary data system (you can see this in the lib/data folder of JUML), for you it could either be something of the sort, or directly what JHipster needs.
In both case, I'm all for it.
As I said, a first iteration would be to make as services:
```
#parse -> returns what's returned by PegJS (JHipster UML is a consumer)
#parseToJHipsterJSON -> returns what JHipster needs.
```
What you took for hesitation was in fact surprise. I thought you guys had already conceived what we did in JHipster UML (the intermediary data system). If you didn't, then forget what I've said, and let's start to code =)

**Comment by deepu105** [comment]
I havent looked at your intermediary data structure closely, but we should keep that as something internal to JHUML or this lib whereever it fits

For what I meant as usable lets take all the use cases we know so far and analyse

1. JHUML needs entity jsons written in the `.jhipster` directory to run the entity generator on those
2. JDL studio needs the parsed data from pegJs
3. `jhipster:import-jdl` sub generator needs entity json data to run the entity generator on those

1 & 3 can be achieved by parsing the JDL to an array of below structure, lets say we have entity `Foo` and `Bar`

```
[
{
    key: Foo,
    value:{
        "relationships": [],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            }
        ],
        "changelogDate": "20160304042002",
        "dto": "no",
        "service": "no",
        "entityTableName": "foo",
        "pagination": "no"
    }
},
{
    key: Bar,
    value:{
        "relationships": [],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            }
        ],
        "changelogDate": "20160304042002",
        "dto": "no",
        "service": "no",
        "entityTableName": "foo",
        "pagination": "no"
    }
}
]
```
both Jhuml and `import-jdl` subgen will receive this as a return from `jdl.parseToEntity(jdlFileText)`  or `parseToJHipsterJSON`, whichever name we choose, call which can then be written to file system or passed to a subgenerator for processing

In case of JDL studio just getting the current pegjs output would be sufficient.

What concerns do you see in this approach? I dont see any dependency here as well this lib will be standalone and JHUML, Jhipster and JDL studio will use the lib to do the work

This way you can remove all JDL related code form JHUML and keep only UML related stuff. In fact if we have a sub generator to process JDL to entity then there wont be a need to process JDL in JHUML at all and JHUML can be purely for UML

**Comment by deepu105** [comment]
From JHUML code I think below can be moved here, correct me if im wrong

1. `dsl_parser.js` (its dependencies can be simplified and inlined as they are just utils)
2. `scheduler.js` this seems to be used as a common thing for all parsers and hence might have to be duplicated or we need to find a way 
3. `EntitiesCreator` this also seems to be common for all parser

may be the `dsl_parser.js` should directly create the result of `EntitiesCreator.createEntities` without  any intermediates

**Comment by MathieuAA** [comment]
The DSLparser has to move here, yes, absolutely. The scheduler stays in JHipster UML, as it has to be used by JHipster, so **for now** it's best to keep it in JUML.
The entiesCreator needs to be cut. I don't know if we should move it here though... I'm testing some new things with it, and it will really change in the near future (some new classes will be created, and some of them may move here instead so that you and everyone else may use them).
The DSLParser needs to be changed to fit your needs. It fits mine as it produces the intermediary data system, but not yours yet. Gotta change it.
EntitiesCreator produces the JSONs, but from our data system.

Concerning the Scheduler, JHipster needs an API (some kind of require("jhipster")). I've already discussed this with Julien a while back, but with this project's birth, I think it's best to keep it simple for now and move things other than the DSL away later (i.e when this project is stable).

The DSL parser doesn't have to know the final output. It would have two roles if it did.

**Comment by MathieuAA** [comment]
@deepu105 I've just pushed a first version of what's available in JHipster UML right here.
It includes the fix I've done a few hours ago, and I won't update the JDL code in JHipster UML.

**Comment by MathieuAA** [comment]
@jdubois Hi Julien, can you allow Travis to scan this project?

**Comment by jdubois** [comment]
@MathieuAA it's done :-)

**Comment by MathieuAA** [comment]
Thanks!

**Comment by deepu105** [comment]
Ill take look :)

**Comment by deepu105** [comment]
@MathieuAA I suppose we need to bring in the functionality of converting the intermediate to jhipster entity json format as well for this to be usable in the main generator?

**Comment by MathieuAA** [comment]
It's not a hard thing to do, and that's a reason why a JHipster API is needed here. 
However, I strongly recommend using an intermediary here. Something that will take what's returned by PegJS, and return an intermediary format for you to use. This intermediary format should be the **only** format you'd have to work with in order to export to a readable JSON for JHipster, as it will protect you from changes in the grammar. 
Here's the flow: 
PegJS | -> PegJS JSON -> | IntermediaryFormatConverter | -> { toJHipsterJSON, etc. }

If it's not done in v1.0.0, it will be in v1.0.1. The JHipster UML intermediary is well-suited for this task (we'd have no dependency problem, neither would you), it would require some kind of polishing though, nothing serious.

To answer your question Deepu, **yes**. We just need to determine how we proceed.

**Comment by deepu105** [comment]
since jhipster is a yeoman generator Im not sure how we can expose it as an API.

Sorry I might have missed something somewhere why again is JHipster needed here? I couldn't recall

for now the only formats that I could think of that will be useful are these

1. JHipster JSON for JHUML and jdl sub generator
2. peg js output for JDL studio

where do you see use case for another intermediary and why?

**Comment by MathieuAA** [comment]
The use case for not another intermediary is simple. Suppose you want to change the way PegJS returns the data because it's too heavy (it currently is by the way), so you decide to clean up the mess and when you're done you notice that what's returned is in fact so pretty that it breaks your code ;-(.
What PegJS returns isn't an intermediary but a POJO (replace the J by Javascript or JSON =)) that shouldn't be directly used by the outside world as:
  - we can easily change it (and break any dependent code);
  - PegJS may decide to change some things too.

The need of an intermediary is simple as that: public methods don't change (or rarely), and keep the same behavior because private methods are allowed to change as often as they need as they shouldn't be used by the outside world.

To be honest, I don't understand why you directly used the output from PegJS.

---

As for JHipster, the need of an API is simply to allow others (me for instance) to know some things:
  - the database types,
  - the types for each database type (and constraints),
  - what's needed to compose a valid JHipster JSON,
  - ...

Notice that, for my last example, I mentioned something quite messy in JHipster's code. Each time you guys want to add something to the JSON you need to make a lot of changes (for instance, 'entityTableName' is mentionned 17 times in generators/entity/index.js). And we, consumers, need to propagate such changes manually (JHipster UML's entity creator is really the ugly). It shouldn't be the case.

I'm not trashing how JHipster's code is made, or how it is organized. I'm just complaining about the lack of flexibility and openness introduced by the fact that JHipster is a Yeoman generator.

---

You don't need to expose JHipster (as a whole) as an API. You guys introduced the module system, that's a first step towards openness. Nothing prevents you from creating a simple file and exposing it to others... That's the case here. This project doesn't need to be exposed by NPM (github can host it), and we can do something like [having git urls as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), it could be available by NPM though.

Sorry for the long post.

**Comment by deepu105** [comment]
1. To me PegJs output is just another JSON and I already have an intermediate form for JDL studio which I obtain by parsing the pegJS output. So unless we can agree on some intermediate form which is usable everywhere there is no much value in it. In the end what is ideal would be to remove JDL support from JHUML as it is redundant now. so that leaves 2 consumers for now JDL studio and import-jdl sub generator.

for JDL studio I need the output from pegJS or something similar to that if you really want to do an intermediate. (Lets be practical, I'm still not convinced that you need an intermediate coz pegJS is nothing but a parser generator so its upto us to define the output format. If you think its heavy we should trim it down at generation itself. It will change only if we change it and we will change it only if it can be propagated as well, mean intermediate will also change so whats the point actually? I mean why would you change pegJS output but not change the intermediate)

for import-jdl im not concerned about pegjs output or the intermediate I just  want JHipster entity jsons for that.

2. For the data you want from Jhipster its all hardcoded and distributed for now and it a huge task to refactor all that to reusable module, yes it can be done and I would like it that way as well but thats gonna take some time and I dont think that would be a priority at this point.
Ill see what can be done for this.

3. The git url dependency is very ugly IMO it would be better to rather host it in NPM itself

**Comment by MathieuAA** [comment]
Oh yes it's ugly, but simple (having a git url, that is) in terms of releases (rollbacks would be possible) but there's still the trust issue you discussed some time ago.
The goal of an intermediary is to take all the fire from what's returned from PegJS, but it remains an **interface**. The interface always provides the same things (more or less, but rarely change), the work to provide the things can change (private methods).
I want to change what's returned by PegJS so that our work is easier.

Can you describe briefly what you implemented for the JDL studio? The intermediary I mean. So that I can see if I can do the same for JHipster UML. We used a format that we **heavily** changed recently (v1.6.0), and I'd like to perfect it a bit more.

**Comment by deepu105** [comment]
Since I made JDL studio based on nomnoml I preferred the format it had as it was easier to render on canvas I just tweaked it a little. you can see the conversion [here](https://github.com/jhipster/jdl-studio/blob/gh-pages/nomnoml/nomnoml.parser.js#L28) 

I dont think this will be much use for you as this is purely for drawing the UML like model on canvas

**Comment by deepu105** [comment]
anyway lets tackle the re usability part later as the types you need to manage today is not that huge, we can see how we can make it common later
