### ISSUE TITLE
How to add an attribute to a relation ?

### ISSUE THREAD

**Issue by chris2338** [jhipster/jhipster-domain-language#20]
For example if I want a relation between a "user" entity and a "forum" entity with a role attribute what is the good way to do with the jdl language ?

```
entity Forum {	
    name String required
}

entity User{	
    login String required
}

/** each user can have an unique role in several forums  
* How do that ?
*/
relationship ManyToMany {
	User{forums} to Forum{users}
}
```

**Comment by MathieuAA** [comment]
I'm not sure I understand the question, can you elaborate?

**Comment by chris2338** [comment]
I just want to be able to add an extra column in the table of the relationship as in this example: 
[many-to-many-extra-fields](http://www.codejava.net/images/articles/frameworks/hibernate/many-to-many-extra-fields/many_to_many_relationship_updated_1.png)

How to do with jdl to add the activated field in the users_groups relation as in this example ?

**Comment by MathieuAA** [comment]
We can't add it from the JDL. @jhipster/developers is it possible to have such a thing with the Q&As?

**Comment by cbornet** [comment]
The example uses ManyToOne/OneToMany with an explicit "link" relationship so that's totally doable with JDL (solution 1 of the example)
Something like
```
entity Forum {  
    name String required
}

entity User{    
    login String required
}

entity UserForum{    
    myAdditionalField String
}

relationship OneToMany {
    User{} to UserForum{}
}

relationship OneToMany {
    Forum{} to UserForum{}
}

relationship ManyToOne {
    UserForum{} to User{}
}

relationship ManyToOne {
    UserForum{} to Forum{}
}
```

**Comment by MathieuAA** [comment]
Seems like overkill. When using the standard generator, if there's no way to add another field in the created table for a MtM, then I guess it's wanted.
Closing this unless there's any objection.

**Comment by chris2338** [comment]
@cbornet I have already used your solution but I was wondering if there was a better solution. With this solution we transform a relationship to an entity

> Seems like overkill. When using the standard generator, if there's no way to add another field in the created table for a MtM, then I guess it's wanted.

@MathieuAA Do you mean that you will develop a new feature enhancement ?

**Comment by MathieuAA** [comment]
No, I meant that I won't do anything unless there's a reason. **If** this is not available with the Q&As, then there must be a reason (i.e. easier to do it in Java, or not frequent a task), and I won't add it because it would require a special kind of post-processing that I'm not really willing to make (and create). If, however, this is already possible, I'll add it right away.
I don't know if Christophe's way works, but I think it does... it's just too much work for so small an effect in my opinion.

**Comment by chris2338** [comment]
Ok. Thank you for your answer. I close this issue.

**Comment by SWEnthusiast** [comment]
Hi @chris2338 did your problem solve? I ran into a similar issue, my requirement is to display the attributes in a column which have **many to many** relationship two different entities. 

Here is my jdl 
```
entity Country {
	countryCode String maxlength(2) required,
	countryName String required,
	affiliateCountryCode String maxlength(3)
}
entity State {
	stateCode String required,
	stateName String required
}
entity Warehouse {
	warehouseId String maxlength(3) required,
	warehouseName String required,	
	addressLine1 String required,
	addressLine2 String, 
	city String required,
	state String required,
	postalCode String required,
	country String required,
	deliveryWarehouse Flag required,
	pickUpCenter Flag required,
	storeFlag Flag required,	
	wmsWarehouseArea WMS required, 
	wmsWarehouseId String required
}
entity WarehouseCountry {
}
entity DefaultWarehouseAssignment {
	postalCode String required,
	startDate ZonedDateTime required,
	endDate ZonedDateTime required,
	altWarehouseAllowed Flag required
}
relationship OneToMany {
	Country to State{country(countryName)}
}
relationship ManyToMany {
	WarehouseCountry{country(countryCode)} to Country,
	WarehouseCountry{warehouse(warehouseId)} to Warehouse 
}
relationship ManyToOne {
	DefaultWarehouseAssignment{country(countryCode)} to Country, 
	DefaultWarehouseAssignment{warehouse(warehouseId)} to Warehouse,
	DefaultWarehouseAssignment{state(stateCode)} to State
}
enum Flag {
	Y, N
}
enum WMS {
	W, S, NONE
}
// Set pagination options
paginate * with pagination
//Creates DTO's and maps the fields using mapstruct generator
dto * with mapstruct
//Creates service classes, which will make the resource call the service class which will call the repository interface
service all with serviceClass
//To generate microservices for entities, will be used by the front-end application
microservice * with wrpServices
//For search by keyword
search * with elasticsearch
```


@cbornet could you suggest a different solution if there is any?

**Comment by briantopping** [comment]
Hi there, congrats on great work here with JDL. @MathieuAA, I am not clear on your reference to the "example" in https://github.com/jhipster/jhipster-core/issues/20#issuecomment-219661649. I assume the documentation has changed, would you know where that reference moved to?

As an aside, being able to add attributes to a MtM is a common advanced usage. It's one part of the first model I have developed with JDL. I imagine it could be tricky to develop and support though. Not critical here, just wanted to register interest in the feature. :)

**Comment by MathieuAA** [comment]
@briantopping Hi, even tough I'd recommend not comment on an old post, I think Christophe simulated a many-to-many relationship without actually having one. It could work but I admit I didn't try this one out (and am certainly not willing to add it to the documentation as it's not a standard way of achieving this kind of relationship).

**Comment by briantopping** [comment]
Thanks @MathieuAA. I definitely thought a lot about commenting on an old, closed issue. The other option was creating a new issue, only to have it annoy as a duplicate and be closed. And I thought about whether I could create a patch since I have a lot of ancient ORM experience with XMI and XDoclet 2. But the reality there is complex patches don't usually get accepted from new committers on an established project, especially if there is a perception that they will not be around to maintain it (I would not). I definitely recognize the size of the ask and don't want to mistake that I am not actually asking for the code to be written, I was just looking for the docs that seemed to be referenced.

I did use what @cbornet posted but found it unusable for more than a POC. Which is fine, like I mentioned I wasn't interested in rehashing all of this. The tools are extremely useful for their intended scope and I got the feeling from reading this thread that my usage is outside the intended scope. That's totally fair, but nobody reads minds to know that they are not the only person to have this goal. Recording it is part of the open source process! It will show up in Google and someone will save some time.

In the end, this is for a project that I am mentoring some college seniors with. I'm going to suggest that they use the tools to generate basic services and CRUD UI, then hand code the MtM glue as "the hard part". It will be a great challenge for them.

Thanks again for a great effort here!

**Comment by MathieuAA** [comment]
@briantopping Good idea :) Like you said, it's open source. If you submit something that gets accepted and not be around to maintain it, it's ok.  It's open source so everyone can pick up :)

**Comment by poneil** [comment]
I agree with Brian: this is a common scenario. I like to call it "decorating" the many-to-many (MtM) relationship. The join table should have it's PK be the IDs of the two (or more, I guess) related tables and the "decoration" are the additional fields. On the JPA side, a OneToMany relationship is created between each related Object and a "join" Object. The join Object, which contains the additional fields is best defined, IMO, with JPA AssociationOverride(s) annotation, and it's ID is an EmbeddedId Object which defines the OneToMany relationship back to the related Objects. I do this all the time and I think it best represents the datamodel.
I don't honestly think the JPA side would be too hard to develop as an option... If an entity is defined in JDL Studio that contains additional fields and is involved in a MtM relationship, the app pumps out the complex AssociationOverride(s) join Object described. In the UI, you want to be able to CRUD that join Object as a part of editing one or the other related Objects, though, not on it's own as a separate entity. It doesn't "mean" anything, on it's own, which is what you get, currently, when you treat the relationship as a OtM + MtO "bridge", so to speak, as is described in some of the posts, above. Nobody wants to know/see what a "UserForum" is. The User is related to Forum(s) and vice-versa. Maybe the additional field is that a forum is a Favorite or it is Required... The app can produce a way to add a Forum to a User and present the additional fields to fill in, which admittedly, seems kind of involved. I'd love to take this on, if I had some time.
