### ISSUE TITLE
Add option to make Entity extend AbstractAuditingEntity

### ISSUE THREAD

**Issue by tkp1n** [jhipster/jhipster-domain-language#24]
Entities created from JDL never extend AbstractAuditingEntity. this should be an option as the DTO, pageable, etc.

**Comment by MathieuAA** [comment]
Hello! Entities (that are not created from JDL code) never extend AbstractAuditingEntity either by default... unless you manually extend make the class extend AbstractAuditingEntity, that or my knowledge is outdated.
That being said, I suggest you drop by JHipster's issue tracker and ask for it.

**Comment by srkhan** [comment]
Hi MathieuAA, 

Even when I extended my Entity with AbstractAuditingEntity, it's still not generating the auditing columns in the database. Can you please advise?
I have also marked columns such as createdBy, createdDate commenting @JsonIgnore referring to some stackflow post but still columns are not being generated in the database.

**Comment by deepu105** [comment]
@srkhan what you are looking for is the entity auditing module.  Check out our modules page in the documentation site. https://github.com/hipster-labs/generator-jhipster-entity-audit

**Comment by srkhan** [comment]
Hi Deepu,

Thank you very much for pointing in the right direction. It works pretty well and I could relate it to Hibernate envers and it's perfect auditing solution. Highly appreciate your efforts to make this availalble as module for JHipster and reducing all the tedious work for envers configuration.

Only one small **bug** I would like to report (Or may be I am not getting it correct with this module) - When you update an entity it updates both **CREATED_DATE** & **LAST_MODIFIED_DATE** in the main entity to same value. I feel it should not be the case. CREATED_DATE should be populated only when the entity was first created. When we make an update to the entity instance it should only update LAST_MODIFIED_BY and LAST_MODIFIED_DATE.

Kindly advise if this can be fixed with some workaround in current release for jhipster-entity-audit module or should we wait for next release?

**Comment by deepu105** [comment]
You are welcome srkhan.

Thats strange what you said, I never noticed such a behavior. Ill try to
check when I find time. The created and modified fields are set by Spring
on the entity itself. So if there is a bug here it might be on the spring
side.

Thanks & Regards,
Deepu

**Comment by tibistibi** [comment]
for the update problem of the created field check you table defenition is not like this:

` created_date       | timestamp    | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |`
